package config;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/api/openapi.json")
public class SwaggerConfigServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        resp.setContentType("application/json;charset=UTF-8");

        // Note: OpenAPI JSON is built dynamically in this servlet. Do not rely on
        // a static file under src/main/webapp/api (per project rules).
        // =========================
        // ===== API: /api/login ===
        // =========================
        // Cập nhật Login (Thêm note reCAPTCHA)
        String loginPath = "\"/api/login\":{"
                + "\"post\":{"
                + "\"tags\":[\"Auth\"],"
                + "\"summary\":\"Login (Verify reCAPTCHA)\","
                + "\"requestBody\":{\"required\":true,\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/LoginRequest\"}}}},"
                + "\"responses\":{"
                + "\"200\":{\"description\":\"OK\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/LoginResponse\"}}}},"
                + "\"400\":{\"description\":\"Invalid reCAPTCHA or Credentials\"},"
                + "\"401\":{\"description\":\"Unauthorized\"}"
                + "}"
                + "}"
                + "}";

        // ================================
        // ===== API: /api/register =======
        // ================================
        // Cập nhật Register (Thêm note reCAPTCHA)
        String registerPath = "\"/api/register\":{"
                + "\"post\":{"
                + "\"tags\":[\"Auth\"],"
                + "\"summary\":\"Register new user (Verify reCAPTCHA)\","
                + "\"requestBody\":{\"required\":true,\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/RegisterRequest\"}}}},"
                + "\"responses\":{"
                + "\"200\":{\"description\":\"Registered successfully\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/LoginResponse\"}}}},"
                + "\"400\":{\"description\":\"Validation error or Invalid reCAPTCHA\"},"
                + "\"409\":{\"description\":\"Email already exists\"}"
                + "}"
                + "}"
                + "}";

        // ==========================================
        // ===== API: /api/register/send-otp ========
        // ==========================================
        String sendOtpPath
                = "\"/api/register/send-otp\":{"
                + "\"post\":{"
                + "\"summary\":\"Register step 1 - Send OTP to email\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/RegisterRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"OTP sent\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error or invalid input\"},"
                + "\"409\":{\"description\":\"Email already exists\"},"
                + "\"502\":{\"description\":\"Failed to send OTP email\"}"
                + "}"
                + "}"
                + "}";

        // ============================================
        // ===== API: /api/register/verify-otp ========
        // ============================================
        String verifyOtpPath
                = "\"/api/register/verify-otp\":{"
                + "\"post\":{"
                + "\"summary\":\"Register step 2 - Verify OTP & create account\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/VerifyOtpRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"OTP valid, user created, return token & user\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/LoginResponse\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"OTP invalid or expired\"},"
                + "\"409\":{\"description\":\"Email already exists (race condition)\"}"
                + "}"
                + "}"
                + "}";

        // =============================================
        // ===== API: /api/register/resend-otp =========
        // =============================================
        String resendOtpPath
                = "\"/api/register/resend-otp\":{"
                + "\"post\":{"
                + "\"summary\":\"Resend OTP for pending registration\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ResendOtpRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"OTP resent\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"No pending registration for this email\"},"
                + "\"429\":{\"description\":\"Too many resends\"},"
                + "\"502\":{\"description\":\"Failed to send OTP email\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/reset-password (EMAIL + OTP) =====
        String resetPasswordPath
                = "\"/api/reset-password\":{"
                + "\"post\":{"
                + "\"summary\":\"Reset password bằng email + OTP\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ResetPasswordRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Đổi mật khẩu thành công\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Thiếu dữ liệu hoặc mật khẩu yếu\"},"
                + "\"401\":{\"description\":\"Email/OTP không hợp lệ hoặc OTP đã hết hạn\"},"
                + "\"404\":{\"description\":\"Email không tồn tại trong hệ thống\"},"
                + "\"500\":{\"description\":\"Lỗi server khi cập nhật mật khẩu\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/forgot-password (CHỈ GỬI OTP) =====
        String forgotPasswordPath
                = "\"/api/forgot-password\":{"
                + "\"post\":{"
                + "\"summary\":\"Gửi OTP đặt lại mật khẩu qua email\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ForgotPasswordRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Đã gửi OTP đặt lại mật khẩu tới email\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Email thiếu hoặc không hợp lệ\"},"
                + "\"404\":{\"description\":\"Email không tồn tại trong hệ thống\"},"
                + "\"500\":{\"description\":\"Lỗi server khi gửi email\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/events (GET ALL EVENTS, JWT) =====
        String eventsPath
                = "\"/api/events\":{"
                + "\"get\":{"
                + "\"summary\":\"Get all events (JWT, roles: STUDENT/ORGANIZER/STAFF/ADMIN)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"List of events\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/EventList\"}"
                + "}"
                + "}"
                + "}"
                + "},"
                + "\"401\":{\"description\":\"Unauthorized\"},"
                + "\"403\":{\"description\":\"Forbidden\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/events/detail =====
        String eventDetailPath
                = "\"/api/events/detail\":{"
                + "\"get\":{"
                + "\"summary\":\"Get event detail (JWT required)\","
                + "\"description\":\"Return event detail including venue, speaker and ticket categories\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "    {"
                + "      \"name\":\"id\","
                + "      \"in\":\"query\","
                + "      \"required\":true,"
                + "      \"schema\":{\"type\":\"integer\"},"
                + "      \"description\":\"Event ID\""
                + "    }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Event detail\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/EventDetail\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"401\":{\"description\":\"Unauthorized\"},"
                + "  \"403\":{\"description\":\"Forbidden\"},"
                + "  \"404\":{\"description\":\"Event not found\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/seats =====
        String seatsPath
                = "\"/api/seats\":{"
                + "\"get\":{"
                + "\"summary\":\"Get seats by area (optional: eventId, seatType)\","
                + "\"description\":\"Trả về danh sách ghế theo khu vực (Venue_Area). "
                + "Nếu truyền eventId: status của ghế sẽ là BOOKED/AVAILABLE theo event đó. "
                + "Nếu không truyền eventId: status giữ nguyên như trong DB (ACTIVE/INACTIVE).\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"areaId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID khu vực (area_id trong Venue_Area) chứa sơ đồ ghế\""
                + "  },"
                + "  {"
                + "    \"name\":\"eventId\","
                + "    \"in\":\"query\","
                + "    \"required\":false,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID sự kiện. Nếu truyền, mỗi ghế sẽ được đánh dấu BOOKED nếu đã có vé trong event này, ngược lại AVAILABLE.\""
                + "  },"
                + "  {"
                + "    \"name\":\"seatType\","
                + "    \"in\":\"query\","
                + "    \"required\":false,"
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"description\":\"Loại ghế (VIP / STANDARD / ...)\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Danh sách ghế theo area (và trạng thái theo event nếu có)\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/SeatResponse\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"400\":{"
                + "    \"description\":\"Thiếu hoặc sai areaId / eventId\""
                + "  },"
                + "  \"401\":{"
                + "    \"description\":\"Unauthorized (thiếu/ sai JWT)\""
                + "  },"
                + "  \"500\":{"
                + "    \"description\":\"Lỗi server khi load danh sách ghế\""
                + "  }"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/payment-ticket =====
        String paymentTicketPath
                = "\"/api/payment-ticket\":{"
                + "\"get\":{"
                + "\"summary\":\"Tạo URL thanh toán VNPay cho vé sự kiện\","
                + "\"description\":\"Validate user/event/categoryTicket/seat và redirect sang VNPay Sandbox\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"userId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID người dùng\""
                + "  },"
                + "  {"
                + "    \"name\":\"eventId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID sự kiện\""
                + "  },"
                + "  {"
                + "    \"name\":\"categoryTicketId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID loại vé (VIP / STANDARD)\""
                + "  },"
                + "  {"
                + "    \"name\":\"seatId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID ghế ngồi\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"302\":{"
                + "    \"description\":\"Redirect sang VNPay để thanh toán\""
                + "  },"
                + "  \"400\":{"
                + "    \"description\":\"Tham số không hợp lệ hoặc ghế/loại vé/sự kiện không hợp lệ\""
                + "  },"
                + "  \"500\":{"
                + "    \"description\":\"Lỗi server khi build URL VNPay\""
                + "  }"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/buyTicket =====
        String buyTicketPath
                = "\"/api/buyTicket\":{"
                + "\"get\":{"
                + "\"summary\":\"VNPay return URL - xác nhận thanh toán và tạo vé\","
                + "\"description\":\"VNPay redirect về URL này sau khi thanh toán. Hệ thống sẽ verify chữ ký, kiểm tra mã phản hồi, tạo Bill & Ticket.\","
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"vnp_Amount\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Số tiền VNPay trả về (đơn vị x100)\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_ResponseCode\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Mã kết quả giao dịch (00 = thành công)\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_OrderInfo\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Thông tin order đã encode (userId, eventId, categoryTicketId, seatId, orderType)\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_TxnRef\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Mã tham chiếu giao dịch\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_SecureHash\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Chữ ký bảo mật HMAC SHA512\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Kết quả xử lý thanh toán (text)\","
                + "    \"content\":{"
                + "      \"text/plain\":{"
                + "        \"schema\":{\"type\":\"string\"}"
                + "      }"
                + "    }"
                + "  }"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/staff/checkin =====
        String staffCheckinPath
                = "\"/api/staff/checkin\":{"
                + "\"post\":{"
                + "\"summary\":\"Check-in vé sự kiện bằng ticketId (STAFF/ADMIN)\","
                + "\"description\":\"STAFF hoặc ADMIN dùng ticketId (từ mã QR) để check-in, cập nhật trạng thái CHECKED_IN và thời gian checkin\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"ticketId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID của vé (ticket_id, thường lấy từ QR code\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Check-in thành công\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/CheckinResponse\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"400\":{"
                + "    \"description\":\"Thiếu ticketId, sai ticketId hoặc trạng thái vé không cho phép check-in\""
                + "  },"
                + "  \"401\":{"
                + "    \"description\":\"Unauthorized (thiếu/ sai JWT)\""
                + "  },"
                + "  \"403\":{"
                + "    \"description\":\"Forbidden (role không phải STAFF/ADMIN)\""
                + "  },"
                + "  \"404\":{"
                + "    \"description\":\"Không tìm thấy vé\""
                + "  }"
                + "}"
                + "}"
                + "}";

        // ============================
        // ===== EVENT REQUEST API =====
        // ============================
        // 1) TẠO REQUEST SỰ KIỆN: POST /api/event-requests (ORGANIZER)
        String eventRequestCreatePath
                = "\"/api/event-requests\":{"
                + "\"post\":{"
                + "\"summary\":\"Organizer tạo request đề xuất sự kiện\","
                + "\"description\":\"Chỉ ORGANIZER mới được gọi API này. Tạo một Event_Request với status = PENDING cho sự kiện đề xuất.\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"requestBody\":{"
                + "  \"required\":true,"
                + "  \"content\":{"
                + "    \"application/json\":{"
                + "      \"schema\":{\"$ref\":\"#/components/schemas/CreateEventRequestBody\"}"
                + "    }"
                + "  }"
                + "},"
                + "\"responses\":{"
                + "  \"201\":{"
                + "    \"description\":\"Organizer tạo request sự kiện thành công\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/CreateEventRequestResponse\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"400\":{\"description\":\"Thiếu title hoặc dữ liệu không hợp lệ\"},"
                + "  \"401\":{\"description\":\"Thiếu/Token không hợp lệ\"},"
                + "  \"403\":{\"description\":\"Chỉ ORGANIZER mới được tạo request\"},"
                + "  \"500\":{\"description\":\"Lỗi server khi tạo request\"}"
                + "}"
                + "}"
                + "}";

        // 2) ORGANIZER xem request của chính mình: GET /api/event-requests/my
        String myEventRequestsPath
                = "\"/api/event-requests/my\":{"
                + "\"get\":{"
                + "\"summary\":\"Organizer xem tất cả request sự kiện của chính mình\","
                + "\"description\":\"Chỉ ORGANIZER, trả về danh sách Event_Request mà requester_id = userId trong token (tức các request do chính Organizer đó tạo).\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Danh sách request của Organizer\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{"
                + "          \"type\":\"array\","
                + "          \"items\":{\"$ref\":\"#/components/schemas/EventRequest\"}"
                + "        }"
                + "      }"
                + "    }"
                + "  },"
                + "  \"401\":{\"description\":\"Thiếu/Token không hợp lệ\"},"
                + "  \"403\":{\"description\":\"Chỉ ORGANIZER mới được xem request của mình\"}"
                + "}"
                + "}"
                + "}";

        // 3) STAFF xem tất cả request PENDING: GET /api/staff/event-requests
        String organizerEventRequestsPath
                = "\"/api/staff/event-requests\":{"
                + "\"get\":{"
                + "\"summary\":\"Staff xem tất cả request sự kiện đang PENDING\","
                + "\"description\":\"Chỉ STAFF (hoặc ADMIN nếu hệ thống cho phép). Trả về toàn bộ Event_Request có status = PENDING để Staff xem và chuẩn bị xử lý.\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Danh sách request PENDING của tất cả Organizer\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{"
                + "          \"type\":\"array\","
                + "          \"items\":{\"$ref\":\"#/components/schemas/EventRequest\"}"
                + "        }"
                + "      }"
                + "    }"
                + "  },"
                + "  \"401\":{\"description\":\"Thiếu/Token không hợp lệ\"},"
                + "  \"403\":{\"description\":\"Chỉ STAFF (hoặc ADMIN) mới được xem danh sách request PENDING\"}"
                + "}"
                + "}"
                + "}";

        // 4) STAFF APPROVE / REJECT: POST /api/event-requests/process
        String eventRequestProcessPath
                = "\"/api/event-requests/process\":{"
                + "\"post\":{"
                + "\"summary\":\"Staff duyệt (APPROVE) hoặc từ chối (REJECT) Event Request\","
                + "\"description\":\"Chỉ role STAFF (hoặc ADMIN) được phép xử lý. APPPROVE sẽ tạo Event mới và gán Area nếu không trùng lịch; REJECT chỉ cập nhật trạng thái request.\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ProcessEventRequestBody\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Staff xử lý request thành công (APPROVE hoặc REJECT)\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ProcessEventRequestResponse\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Thiếu dữ liệu hoặc action/areaId không hợp lệ\"},"
                + "\"401\":{\"description\":\"Thiếu hoặc token không hợp lệ\"},"
                + "\"403\":{\"description\":\"Không phải STAFF/ADMIN nên không được xử lý request\"},"
                + "\"404\":{\"description\":\"Không tìm thấy request\"},"
                + "\"409\":{\"description\":\"Khu vực đã có sự kiện trùng thời gian\"},"
                + "\"500\":{\"description\":\"Lỗi server khi xử lý APPROVE/REJECT\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/areas/free ===== (STAFF chọn khu vực trống)
        String freeAreasPath
                = "\"/api/areas/free\":{"
                + "\"get\":{"
                + "\"summary\":\"Staff lấy danh sách khu vực trống với buffer 1h (STAFF/ADMIN)\","
                + "\"description\":\"Check JWT role STAFF/ADMIN, truyền startTime & endTime, trả về danh sách Venue_Area còn trống với buffer 1 giờ để Staff chọn khu vực phù hợp khi duyệt request.\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"startTime\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "    \"description\":\"Thời gian bắt đầu (ISO 8601, ví dụ 2025-12-10T08:00:00)\""
                + "  },"
                + "  {"
                + "    \"name\":\"endTime\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "    \"description\":\"Thời gian kết thúc (sau startTime)\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Danh sách khu vực còn trống để Staff lựa chọn\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/FreeAreasResponse\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"400\":{"
                + "    \"description\":\"Thiếu hoặc sai startTime/endTime\""
                + "  },"
                + "  \"401\":{"
                + "    \"description\":\"Thiếu hoặc token không hợp lệ\""
                + "  },"
                + "  \"403\":{"
                + "    \"description\":\"Không phải STAFF/ADMIN\""
                + "  },"
                + "  \"500\":{"
                + "    \"description\":\"Lỗi server khi truy vấn danh sách khu vực\""
                + "  }"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/venues (CRUD) =====
        String venuesPath
                = "\"/api/venues\":{"
                + "\"get\":{"
                + "\"summary\":\"Xem danh sách địa điểm với khu vực lồng nhau (Nested)\","
                + "\"description\":\"Trả về danh sách Venue kèm theo mảng Areas bên trong (nested JSON response)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"List of venues with nested areas\","
                + "\"content\":{\"application/json\":{"
                + "\"schema\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/Venue\"}"
                + "}"
                + "}"
                + "}"
                + "},"
                + "\"401\":{\"description\":\"Unauthorized\"}"
                + "}"
                + "},"
                + "\"post\":{"
                + "\"summary\":\"Tạo địa điểm mới (Admin)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/VenueCreateRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"201\":{"
                + "\"description\":\"Created\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"401\":{\"description\":\"Unauthorized\"},"
                + "\"403\":{\"description\":\"Forbidden\"}"
                + "}"
                + "},"
                + "\"put\":{"
                + "\"summary\":\"Cập nhật địa điểm (Admin)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/VenueUpdateRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Updated\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"401\":{\"description\":\"Unauthorized\"},"
                + "\"403\":{\"description\":\"Forbidden\"}"
                + "}"
                + "},"
                + "\"delete\":{"
                + "\"summary\":\"Xóa địa điểm (Soft Delete)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "{"
                + "\"name\":\"venueId\","
                + "\"in\":\"query\","
                + "\"required\":true,"
                + "\"schema\":{\"type\":\"integer\"}"
                + "}"
                + "],"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Soft deleted\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"401\":{\"description\":\"Unauthorized\"},"
                + "\"403\":{\"description\":\"Forbidden\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/venues/areas (list by venue + CRUD) =====
        String venueAreasPath
                = "\"/api/venues/areas\":{"
                + "\"get\":{"
                + "\"summary\":\"Lấy danh sách phòng (tất cả hoặc theo VenueID)\","
                + "\"description\":\"Nếu không truyền venueId: trả về TẤT CẢ các khu vực. Nếu có venueId: lọc theo venue đó.\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "{"
                + "\"name\":\"venueId\","
                + "\"in\":\"query\","
                + "\"required\":false,"
                + "\"schema\":{\"type\":\"integer\"},"
                + "\"description\":\"ID của venue (tùy chọn). Bỏ trống để lấy tất cả areas.\""
                + "}"
                + "],"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"List of areas (filtered or all)\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/VenueArea\"}"
                + "}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"401\":{\"description\":\"Unauthorized\"}"
                + "}"
                + "},"
                + "\"post\":{"
                + "\"summary\":\"Thêm phòng vào địa điểm\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/VenueAreaCreateRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"201\":{"
                + "\"description\":\"Created\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"401\":{\"description\":\"Unauthorized\"}"
                + "}"
                + "},"
                + "\"put\":{"
                + "\"summary\":\"Cập nhật thông tin phòng (Admin)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/VenueArea\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Updated\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"401\":{\"description\":\"Unauthorized\"},"
                + "\"403\":{\"description\":\"Forbidden\"}"
                + "}"
                + "},"
                + "\"delete\":{"
                + "\"summary\":\"Xóa phòng (Soft Delete) (Admin)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "{"
                + "\"name\":\"areaId\","
                + "\"in\":\"query\","
                + "\"required\":true,"
                + "\"schema\":{\"type\":\"integer\"}"
                + "}"
                + "],"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Soft deleted\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"401\":{\"description\":\"Unauthorized\"},"
                + "\"403\":{\"description\":\"Forbidden\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/registrations/my-tickets (Student History) =====
        String myTicketsPath
                = "\"/api/registrations/my-tickets\":{"
                + "\"get\":{"
                + "\"summary\":\"[Student] Xem lịch sử vé đã đăng ký\","
                + "\"description\":\"Lấy danh sách vé của user đang đăng nhập (kèm thông tin sự kiện, địa điểm)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Danh sách vé\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{"
                + "          \"type\":\"array\","
                + "          \"items\":{"
                + "            \"type\":\"object\","
                + "            \"properties\":{"
                + "              \"ticketId\":{\"type\":\"integer\", \"example\": 1},"
                + "              \"ticketCode\":{\"type\":\"string\", \"example\": \"QR-123456\"},"
                + "              \"eventName\":{\"type\":\"string\", \"example\": \"Talkshow AI\"},"
                + "              \"venueName\":{\"type\":\"string\", \"example\": \"Hội trường A\"},"
                + "              \"startTime\":{\"type\":\"string\", \"format\":\"date-time\"},"
                + "              \"status\":{\"type\":\"string\", \"example\": \"BOOKED\"},"
                + "              \"checkInTime\":{\"type\":\"string\", \"format\":\"date-time\"}"
                + "            }"
                + "          }"
                + "        }"
                + "      }"
                + "    }"
                + "  },"
                + "  \"401\":{\"description\":\"Chưa đăng nhập\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/events/stats (Thống kê) =====
        String eventStatsPath
                = "\"/api/events/stats\":{"
                + "\"get\":{"
                + "\"summary\":\"[Organizer] Thống kê số lượng tham dự\","
                + "\"description\":\"Đếm tổng số vé đăng ký và số người đã check-in thực tế\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"eventId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID của sự kiện cần xem\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Thông tin thống kê\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{"
                + "          \"type\":\"object\","
                + "          \"properties\":{"
                + "            \"eventId\":{\"type\":\"integer\", \"example\": 1},"
                + "            \"totalRegistered\":{\"type\":\"integer\", \"example\": 100},"
                + "            \"totalCheckedIn\":{\"type\":\"integer\", \"example\": 85},"
                + "            \"checkInRate\":{\"type\":\"string\", \"example\": \"85.0%\"}"
                + "          }"
                + "        }"
                + "      }"
                + "    }"
                + "  },"
                + "  \"403\":{\"description\":\"Không có quyền (Chỉ Organizer/Admin)\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/payment/my-bills (Student Bill History) - UPDATED =====
        String myBillsPath
                = "\"/api/payment/my-bills\":{"
                + "\"get\":{"
                + "\"summary\":\"[Student] Xem lịch sử thanh toán (Bills)\","
                + "\"description\":\"Lấy danh sách hóa đơn thanh toán (hiển thị Tên người dùng thay vì ID)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Danh sách hóa đơn\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{"
                + "          \"type\":\"array\","
                + "          \"items\":{"
                + "            \"type\":\"object\","
                + "            \"properties\":{"
                + "              \"billId\":{\"type\":\"integer\", \"example\": number},"
                + "              \"totalAmount\":{\"type\":\"number\", \"example\": number},"
                + "              \"currency\":{\"type\":\"string\", \"example\": \"string\"},"
                + "              \"paymentMethod\":{\"type\":\"string\", \"example\": \"string\"},"
                + "              \"paymentStatus\":{\"type\":\"string\", \"example\": \"string\"},"
                + "              \"createdAt\":{\"type\":\"string\", \"format\":\"string\"},"
                + "              \"userName\":{\"type\":\"string\", \"example\": \"string\"}" // <--- Thay userId bằng userName                
                + "            }"
                + "          }"
                + "        }"
                + "      }"
                + "    }"
                + "  },"
                + "  \"401\":{\"description\":\"Chưa đăng nhập\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/events/update-details =====
        String updateEventDetailsPath
                = "\"/api/events/update-details\":{"
                + "\"post\":{"
                + "\"summary\":\"Organizer cập nhật chi tiết sự kiện (speaker, tickets, banner, layout ghế)\","
                + "\"description\":\"Chỉ ORGANIZER được phép gọi. Cập nhật speaker, tickets, banner_url và re-config layout ghế cho event.\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"requestBody\":{"
                + "  \"required\":true,"
                + "  \"content\":{"
                + "    \"application/json\":{"
                + "      \"schema\":{\"$ref\":\"#/components/schemas/UpdateEventDetailsRequest\"}"
                + "    }"
                + "  }"
                + "},"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Cập nhật thành công chi tiết sự kiện\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"400\":{\"description\":\"Dữ liệu không hợp lệ (thiếu eventId, tickets, quá max_seats, ...)\"},"
                + "  \"401\":{\"description\":\"Thiếu hoặc token không hợp lệ\"},"
                + "  \"403\":{\"description\":\"Không phải Organizer / không phải owner của event\"},"
                + "  \"404\":{\"description\":\"Không tìm thấy event hoặc event request\"},"
                + "  \"500\":{\"description\":\"Lỗi server khi cập nhật chi tiết sự kiện\"}"
                + "}"
                + "}"
                + "}";

        // ================================
        // ========== GHÉP JSON ===========
        // ================================
        String serverUrl = req.getScheme() + "://" + req.getServerName()
                + ":" + req.getServerPort() + req.getContextPath();

        String json
                = "{"
                + "\"openapi\":\"3.0.1\","
                + "\"info\":{\"title\":\"FPT Event Management API\",\"version\":\"1.0.0\"},"
                + "\"servers\":[{\"url\":\"" + serverUrl + "\"}],"
                + "\"paths\":{"
                + loginPath + ","
                + registerPath + ","
                + sendOtpPath + ","
                + verifyOtpPath + ","
                + resendOtpPath + ","
                + resetPasswordPath + ","
                + forgotPasswordPath + ","
                + eventsPath + ","
                + seatsPath + ","
                + eventDetailPath + ","
                + paymentTicketPath + ","
                + staffCheckinPath + ","
                + eventRequestCreatePath + ","
                + myEventRequestsPath + ","
                + organizerEventRequestsPath + ","
                + eventRequestProcessPath + ","
                + updateEventDetailsPath + ","
                + freeAreasPath + ","
                + buyTicketPath + ","
                + venuesPath + ","
                + venueAreasPath + ","
                + myTicketsPath + ","
                + eventStatsPath + ","
                + myBillsPath
                + "},"
                + "\"components\":{"
                + "\"securitySchemes\":{"
                + "\"bearerAuth\":{"
                + "\"type\":\"http\","
                + "\"scheme\":\"bearer\","
                + "\"bearerFormat\":\"JWT\""
                + "}"
                + "},"
                + "\"schemas\":{"
                // LoginRequest
                + "\"LoginRequest\":{\"type\":\"object\",\"properties\":{"
                + "\"email\":{\"type\":\"string\",\"example\":\"string\"},"
                + "\"password\":{\"type\":\"string\",\"format\":\"password\",\"example\":\"string\"},"
                + "\"recaptchaToken\":{\"type\":\"string\",\"description\":\"Token từ Google\",\"example\":\"TEST_BYPASS\"}"
                + "},\"required\":[\"email\",\"password\"]},"
                // RegisterRequest
                + "\"RegisterRequest\":{\"type\":\"object\",\"properties\":{"
                + "\"fullName\":{\"type\":\"string\",\"example\":\"string\"},"
                + "\"phone\":{\"type\":\"string\",\"example\":\"string\"},"
                + "\"email\":{\"type\":\"string\",\"example\":\"string\"},"
                + "\"password\":{\"type\":\"string\",\"format\":\"password\",\"example\":\"string\"},"
                + "\"recaptchaToken\":{\"type\":\"string\",\"description\":\"Token từ Google\",\"example\":\"TEST_BYPASS\"}"
                + "},\"required\":[\"fullName\",\"phone\",\"email\",\"password\"]},"
                // VerifyOtpRequest
                + "\"VerifyOtpRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"},"
                + "\"otp\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\",\"otp\"]"
                + "},"
                // ResendOtpRequest
                + "\"ResendOtpRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\"]"
                + "},"
                // ResetPasswordRequest
                + "\"ResetPasswordRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"},"
                + "\"otp\":{\"type\":\"string\"},"
                + "\"newPassword\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\",\"otp\",\"newPassword\"]"
                + "},"
                // User
                + "\"User\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"id\":{\"type\":\"integer\"},"
                + "\"fullName\":{\"type\":\"string\"},"
                + "\"email\":{\"type\":\"string\"},"
                + "\"phone\":{\"type\":\"string\"},"
                + "\"role\":{\"type\":\"string\"},"
                + "\"status\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // LoginResponse
                + "\"LoginResponse\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"status\":{\"type\":\"string\"},"
                + "\"message\":{\"type\":\"string\"},"
                + "\"token\":{\"type\":\"string\"},"
                + "\"user\":{\"$ref\":\"#/components/schemas/User\"}"
                + "}"
                + "},"
                // ForgotPasswordRequest
                + "\"ForgotPasswordRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\"]"
                + "},"
                // StatusMessage
                + "\"StatusMessage\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"status\":{\"type\":\"string\"},"
                + "\"message\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // EventList
                + "\"EventList\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"eventId\":{\"type\":\"integer\"},"
                + "\"title\":{\"type\":\"string\"},"
                + "\"description\":{\"type\":\"string\"},"
                + "\"startTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"endTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"maxSeats\":{\"type\":\"integer\"},"
                + "\"status\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // CategoryTicket
                + "\"CategoryTicket\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"categoryTicketId\":{\"type\":\"integer\"},"
                + "\"name\":{\"type\":\"string\"},"
                + "\"price\":{\"type\":\"number\",\"format\":\"double\"},"
                + "\"maxQuantity\":{\"type\":\"integer\"},"
                + "\"status\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // Seat
                + "\"Seat\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"seatId\":{\"type\":\"integer\"},"
                + "\"areaId\":{\"type\":\"integer\"},"
                + "\"seatCode\":{\"type\":\"string\"},"
                + "\"rowNo\":{\"type\":\"string\"},"
                + "\"colNo\":{\"type\":\"string\"},"
                + "\"status\":{"
                + "  \"type\":\"string\","
                + "  \"description\":\"Trạng thái ghế. Nếu gọi /api/seats không truyền eventId: giá trị là ACTIVE/INACTIVE (trạng thái vật lý). Nếu có eventId: giá trị là BOOKED hoặc AVAILABLE theo event đó.\""
                + "},"
                + "\"seatType\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // SeatResponse
                + "\"SeatResponse\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"areaId\":{\"type\":\"integer\"},"
                + "\"seatType\":{\"type\":\"string\"},"
                + "\"total\":{\"type\":\"integer\"},"
                + "\"seats\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/Seat\"}"
                + "}"
                + "}"
                + "},"
                // EventDetail
                + "\"EventDetail\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"eventId\":{\"type\":\"integer\"},"
                + "\"title\":{\"type\":\"string\"},"
                + "\"description\":{\"type\":\"string\"},"
                + "\"startTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"endTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"maxSeats\":{\"type\":\"integer\"},"
                + "\"status\":{\"type\":\"string\"},"
                + "\"venueName\":{\"type\":\"string\"},"
                + "\"speakerName\":{\"type\":\"string\"},"
                + "\"tickets\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/CategoryTicket\"}"
                + "}"
                + "}"
                + "},"
                // UpdateEventDetailsRequest
                + "\"UpdateEventDetailsRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "  \"eventId\":{\"type\":\"integer\"},"
                + "  \"speaker\":{\"$ref\":\"#/components/schemas/SpeakerDTO\"},"
                + "  \"tickets\":{"
                + "    \"type\":\"array\","
                + "    \"items\":{\"$ref\":\"#/components/schemas/TicketDTO\"}"
                + "  },"
                + "  \"bannerUrl\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"eventId\",\"tickets\"]"
                + "},"
                // SpeakerDTO
                + "\"SpeakerDTO\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "  \"fullName\":{\"type\":\"string\"},"
                + "  \"bio\":{\"type\":\"string\"},"
                + "  \"email\":{\"type\":\"string\"},"
                + "  \"phone\":{\"type\":\"string\"},"
                + "  \"avatarUrl\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // TicketDTO
                + "\"TicketDTO\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "  \"name\":{\"type\":\"string\"},"
                + "  \"description\":{\"type\":\"string\"},"
                + "  \"price\":{\"type\":\"number\",\"format\":\"double\"},"
                + "  \"maxQuantity\":{\"type\":\"integer\"},"
                + "  \"status\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"name\",\"price\",\"maxQuantity\"]"
                + "},"
                // CheckinResponse
                + "\"CheckinResponse\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"message\":{\"type\":\"string\"},"
                + "\"ticketId\":{\"type\":\"integer\"},"
                + "\"status\":{\"type\":\"string\"},"
                + "\"checkinTime\":{\"type\":\"string\",\"format\":\"date-time\"}"
                + "}"
                + "},"
                // Body tạo Event Request
                + "\"CreateEventRequestBody\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"title\":{\"type\":\"string\"},"
                + "\"description\":{\"type\":\"string\"},"
                + "\"preferredStartTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"preferredEndTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"expectedCapacity\":{\"type\":\"integer\"}"
                + "},"
                + "\"required\":[\"title\",\"preferredStartTime\",\"preferredEndTime\"]"
                + "},"
                // Response tạo Event Request
                + "\"CreateEventRequestResponse\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"status\":{\"type\":\"string\"},"
                + "\"message\":{\"type\":\"string\"},"
                + "\"requestId\":{\"type\":\"integer\"}"
                + "}"
                + "},"
                // EventRequest DTO
                + "\"EventRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"requestId\":{\"type\":\"integer\"},"
                + "\"requesterId\":{\"type\":\"integer\"},"
                + "\"title\":{\"type\":\"string\"},"
                + "\"description\":{\"type\":\"string\"},"
                + "\"preferredStartTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"preferredEndTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"expectedCapacity\":{\"type\":\"integer\"},"
                + "\"status\":{\"type\":\"string\"},"
                + "\"createdAt\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"processedBy\":{\"type\":\"integer\"},"
                + "\"processedAt\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"organizerNote\":{\"type\":\"string\"},"
                + "\"createdEventId\":{\"type\":\"integer\"}"
                + "}"
                + "},"
                // Body xử lý APPROVE/REJECT
                + "\"ProcessEventRequestBody\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"requestId\":{\"type\":\"integer\"},"
                + "\"action\":{\"type\":\"string\",\"description\":\"APPROVE hoặc REJECT\"},"
                + "\"organizerNote\":{\"type\":\"string\"},"
                + "\"areaId\":{\"type\":\"integer\",\"description\":\"Bắt buộc khi action = APPROVE\"}"
                + "},"
                + "\"required\":[\"requestId\",\"action\"]"
                + "},"
                // Response xử lý APPROVE/REJECT
                + "\"ProcessEventRequestResponse\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"status\":{\"type\":\"string\"},"
                + "\"message\":{\"type\":\"string\"},"
                + "\"eventId\":{\"type\":\"integer\"}"
                + "}"
                + "},"
                // VenueArea
                + "\"VenueArea\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"areaId\":{\"type\":\"integer\"},"
                + "\"venueId\":{\"type\":\"integer\"},"
                + "\"areaName\":{\"type\":\"string\"},"
                + "\"floor\":{\"type\":\"integer\"},"
                + "\"capacity\":{\"type\":\"integer\"},"
                + "\"status\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // FreeAreasResponse
                + "\"FreeAreasResponse\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"status\":{\"type\":\"string\"},"
                + "\"startTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"endTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"bufferHours\":{\"type\":\"integer\"},"
                + "\"total\":{\"type\":\"integer\"},"
                + "\"areas\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/VenueArea\"}"
                + "}"
                + "}"
                + "},"
                // Venue (with nested areas)
                + "\"Venue\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"venueId\":{\"type\":\"integer\"},"
                + "\"venueName\":{\"type\":\"string\"},"
                + "\"address\":{\"type\":\"string\"},"
                + "\"status\":{\"type\":\"string\"},"
                + "\"areas\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/VenueArea\"}"
                + "}"
                + "}"
                + "},"
                // VenueCreateRequest
                + "\"VenueCreateRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"venueId\":{\"type\":\"integer\"},"
                + "\"venueName\":{\"type\":\"string\"},"
                + "\"address\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"venueName\"]"
                + "},"
                + "\"VenueUpdateRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"venueId\":{\"type\":\"integer\"},"
                + "\"venueName\":{\"type\":\"string\"},"
                + "\"address\":{\"type\":\"string\"},"
                + "\"status\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"venueId\",\"venueName\",\"address\",\"status\"],"
                + "\"example\":{\"venueId\":0,\"venueName\":\"string\",\"address\":\"string\",\"status\":\"AVAILABLE\"}"
                + "},"
                // VenueAreaCreateRequest
                + "\"VenueAreaCreateRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"venueId\":{\"type\":\"integer\"},"
                + "\"areaName\":{\"type\":\"string\"},"
                + "\"floor\":{\"type\":\"integer\"},"
                + "\"capacity\":{\"type\":\"integer\"}"
                + "},"
                + "\"required\":[\"venueId\",\"areaName\",\"capacity\"]"
                + "}"
                + "}" // end schemas
                + "}" // end components
                + "}";  // end root

        try ( PrintWriter out = resp.getWriter()) {
            out.print(json);
            out.flush();
        }
    }
}
