package config;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/api/openapi.json")
public class SwaggerConfigServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {

        resp.setContentType("application/json;charset=UTF-8");

        // =========================
        // ===== API: /api/login ===
        // =========================
        String loginPath
                = "\"/api/login\":{"
                + "\"post\":{"
                + "\"summary\":\"Login\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/LoginRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"OK\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/LoginResponse\"}"
                + "}"
                + "}"
                + "},"
                + "\"401\":{\"description\":\"Unauthorized\"}"
                + "}"
                + "}"
                + "}";

        // ================================
        // ===== API: /api/register =======
        // ================================
        String registerPath
                = "\"/api/register\":{"
                + "\"post\":{"
                + "\"summary\":\"Register new user (no OTP)\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/RegisterRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Registered successfully (returns token & user)\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/LoginResponse\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error\"},"
                + "\"409\":{\"description\":\"Email already exists\"}"
                + "}"
                + "}"
                + "}";

        // ==========================================
        // ===== API: /api/register/send-otp ========
        // ==========================================
        String sendOtpPath
                = "\"/api/register/send-otp\":{"
                + "\"post\":{"
                + "\"summary\":\"Register step 1 - Send OTP to email\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/RegisterRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"OTP sent\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Validation error or invalid input\"},"
                + "\"409\":{\"description\":\"Email already exists\"},"
                + "\"502\":{\"description\":\"Failed to send OTP email\"}"
                + "}"
                + "}"
                + "}";

        // ============================================
        // ===== API: /api/register/verify-otp ========
        // ============================================
        String verifyOtpPath
                = "\"/api/register/verify-otp\":{"
                + "\"post\":{"
                + "\"summary\":\"Register step 2 - Verify OTP & create account\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/VerifyOtpRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"OTP valid, user created, return token & user\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/LoginResponse\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"OTP invalid or expired\"},"
                + "\"409\":{\"description\":\"Email already exists (race condition)\"}"
                + "}"
                + "}"
                + "}";

        // =============================================
        // ===== API: /api/register/resend-otp =========
        // =============================================
        String resendOtpPath
                = "\"/api/register/resend-otp\":{"
                + "\"post\":{"
                + "\"summary\":\"Resend OTP for pending registration\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ResendOtpRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"OTP resent\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"No pending registration for this email\"},"
                + "\"429\":{\"description\":\"Too many resends\"},"
                + "\"502\":{\"description\":\"Failed to send OTP email\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/reset-password START =====
        String resetPasswordPath
                = "\"/api/reset-password\":{"
                + "\"post\":{"
                + "\"summary\":\"Reset password bằng OTP\"," 
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ResetPasswordRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Đổi mật khẩu thành công\"," 
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Thiếu dữ liệu hoặc mật khẩu yếu\"},"
                + "\"401\":{\"description\":\"OTP không hợp lệ\"},"
                + "\"500\":{\"description\":\"Lỗi server khi cập nhật mật khẩu\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/forgot-password START =====
        String forgotPasswordPath
                = "\"/api/forgot-password\":{"
                + "\"post\":{"
                + "\"summary\":\"Gửi OTP và token đặt lại mật khẩu qua email\","
                + "\"requestBody\":{"
                + "\"required\":true,"
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/ForgotPasswordRequest\"}"
                + "}"
                + "}"
                + "},"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"Đã gửi OTP và link đặt lại mật khẩu\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{\"$ref\":\"#/components/schemas/StatusMessage\"}"
                + "}"
                + "}"
                + "},"
                + "\"400\":{\"description\":\"Email thiếu hoặc không hợp lệ\"},"
                + "\"404\":{\"description\":\"Email không tồn tại trong hệ thống\"},"
                + "\"500\":{\"description\":\"Lỗi server khi gửi email\"}"
                + "}"
                + "}"
                + "}";

        // ===== API: /api/events (GET ALL EVENTS, JWT) =====
        String eventsPath
                = "\"/api/events\":{"
                + "\"get\":{"
                + "\"summary\":\"Get all events (JWT, roles: STUDENT/ORGANIZER/STAFF/ADMIN)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"responses\":{"
                + "\"200\":{"
                + "\"description\":\"List of events\","
                + "\"content\":{"
                + "\"application/json\":{"
                + "\"schema\":{"
                + "\"type\":\"array\","
                + "\"items\":{\"$ref\":\"#/components/schemas/EventList\"}"
                + "}"
                + "}"
                + "}"
                + "},"
                + "\"401\":{\"description\":\"Unauthorized\"},"
                + "\"403\":{\"description\":\"Forbidden\"}"
                + "}"
                + "}"
                + "}";

        String eventDetailPath
                = "\"/api/events/detail\":{"
                + "\"get\":{"
                + "\"summary\":\"Get event detail (JWT required)\","
                + "\"description\":\"Return event detail including venue, speaker and ticket categories\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "    {"
                + "      \"name\":\"id\","
                + "      \"in\":\"query\","
                + "      \"required\":true,"
                + "      \"schema\":{\"type\":\"integer\"},"
                + "      \"description\":\"Event ID\""
                + "    }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Event detail\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/EventDetail\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"401\":{\"description\":\"Unauthorized\"},"
                + "  \"403\":{\"description\":\"Forbidden\"},"
                + "  \"404\":{\"description\":\"Event not found\"}"
                + "}"
                + "}"
                + "}";
        
          String seatsPath
                = "\"/api/seats\":{"
                + "\"get\":{"
                + "\"summary\":\"Get seats by area & optional seatType (JWT)\","
                + "\"description\":\"Trả về danh sách ghế theo khu vực (Venue_Area), có thể lọc theo loại ghế (VIP/STANDARD/...)\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"areaId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID khu vực (area_id trong Venue_Area) chứa sơ đồ ghế\""
                + "  },"
                + "  {"
                + "    \"name\":\"seatType\","
                + "    \"in\":\"query\","
                + "    \"required\":false,"
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"description\":\"Loại ghế (VIP / STANDARD / ...)\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Danh sách ghế theo area (và loại ghế nếu có)\","
                + "    \"content\":{"
                + "      \"application/json\":{"
                + "        \"schema\":{\"$ref\":\"#/components/schemas/SeatResponse\"}"
                + "      }"
                + "    }"
                + "  },"
                + "  \"400\":{"
                + "    \"description\":\"Thiếu hoặc sai areaId\""
                + "  },"
                + "  \"401\":{"
                + "    \"description\":\"Unauthorized (thiếu/ sai JWT)\""
                + "  },"
                + "  \"500\":{"
                + "    \"description\":\"Lỗi server khi load danh sách ghế\""
                + "  }"
                + "}"
                + "}"
                + "}";

        String paymentTicketPath
                = "\"/api/payment-ticket\":{"
                + "\"get\":{"
                + "\"summary\":\"Tạo URL thanh toán VNPay cho vé sự kiện\","
                + "\"description\":\"Validate user/event/categoryTicket/seat và redirect sang VNPay Sandbox\","
                + "\"security\":[{\"bearerAuth\":[]}],"
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"userId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID người dùng\""
                + "  },"
                + "  {"
                + "    \"name\":\"eventId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID sự kiện\""
                + "  },"
                + "  {"
                + "    \"name\":\"categoryTicketId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID loại vé (VIP / STANDARD)\""
                + "  },"
                + "  {"
                + "    \"name\":\"seatId\","
                + "    \"in\":\"query\","
                + "    \"required\":true,"
                + "    \"schema\":{\"type\":\"integer\"},"
                + "    \"description\":\"ID ghế ngồi\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"302\":{"
                + "    \"description\":\"Redirect sang VNPay để thanh toán\""
                + "  },"
                + "  \"400\":{"
                + "    \"description\":\"Tham số không hợp lệ hoặc ghế/loại vé/sự kiện không hợp lệ\""
                + "  },"
                + "  \"500\":{"
                + "    \"description\":\"Lỗi server khi build URL VNPay\""
                + "  }"
                + "}"
                + "}"
                + "}";

        String buyTicketPath
                = "\"/api/buyTicket\":{"
                + "\"get\":{"
                + "\"summary\":\"VNPay return URL - xác nhận thanh toán và tạo vé\","
                + "\"description\":\"VNPay redirect về URL này sau khi thanh toán. Hệ thống sẽ verify chữ ký, kiểm tra mã phản hồi, tạo Bill & Ticket.\","
                + "\"parameters\":["
                + "  {"
                + "    \"name\":\"vnp_Amount\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Số tiền VNPay trả về (đơn vị x100)\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_ResponseCode\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Mã kết quả giao dịch (00 = thành công)\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_OrderInfo\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Thông tin order đã encode (userId, eventId, categoryTicketId, seatId, orderType)\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_TxnRef\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Mã tham chiếu giao dịch\""
                + "  },"
                + "  {"
                + "    \"name\":\"vnp_SecureHash\","
                + "    \"in\":\"query\","
                + "    \"schema\":{\"type\":\"string\"},"
                + "    \"required\":false,"
                + "    \"description\":\"Chữ ký bảo mật HMAC SHA512\""
                + "  }"
                + "],"
                + "\"responses\":{"
                + "  \"200\":{"
                + "    \"description\":\"Kết quả xử lý thanh toán (text)\","
                + "    \"content\":{"
                + "      \"text/plain\":{"
                + "        \"schema\":{\"type\":\"string\"}"
                + "      }"
                + "    }"
                + "  }"
                + "}"
                + "}"
                + "}";

        // ================================
        // ========== GHÉP JSON ===========
        // ================================
        String json
                = "{"
                + "\"openapi\":\"3.0.1\","
                + "\"info\":{\"title\":\"FPT Event Management API\",\"version\":\"1.0.0\"},"
                + "\"servers\":[{\"url\":\"http://localhost:8080/FPTEventManagement\"}],"
                + "\"paths\":{"
                + loginPath + ","
                + registerPath + ","
                + sendOtpPath + ","
                + verifyOtpPath + ","
                + resendOtpPath + ","
                + resetPasswordPath + ","
                + forgotPasswordPath + ","
                + eventsPath + ","
                + seatsPath + ","           
                + eventDetailPath + ","
                + paymentTicketPath + "," // ✅ thêm dòng này
                + buyTicketPath // ✅ và dòng này (không có dấu phẩy phía sau)
                + "},"
                + "\"components\":{"
                // ===== SECURITY SCHEMES (BEARER JWT) =====
                + "\"securitySchemes\":{"
                + "\"bearerAuth\":{"
                + "\"type\":\"http\","
                + "\"scheme\":\"bearer\","
                + "\"bearerFormat\":\"JWT\""
                + "}"
                + "},"
                // ====== SCHEMAS ======
                + "\"schemas\":{"
                // LoginRequest
                + "\"LoginRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"},"
                + "\"password\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\",\"password\"]"
                + "},"
                // RegisterRequest
                + "\"RegisterRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"fullName\":{\"type\":\"string\"},"
                + "\"phone\":{\"type\":\"string\"},"
                + "\"email\":{\"type\":\"string\"},"
                + "\"password\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"fullName\",\"phone\",\"email\",\"password\"]"
                + "},"
                // VerifyOtpRequest
                + "\"VerifyOtpRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"},"
                + "\"otp\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\",\"otp\"]"
                + "},"
                // ResendOtpRequest
                + "\"ResendOtpRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\"]"
                + "},"
                // ResetPasswordRequest (no token, use email + OTP)
                + "\"ResetPasswordRequest\":{"
                + "\"type\":\"object\"," 
                + "\"properties\":{"
                + "\"otp\":{\"type\":\"string\",\"pattern\":\"^[0-9]{6}$\"},"
                + "\"newPassword\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"otp\",\"newPassword\"]"
                + "},"
                // User
                + "\"User\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"id\":{\"type\":\"integer\"},"
                + "\"fullName\":{\"type\":\"string\"},"
                + "\"email\":{\"type\":\"string\"},"
                + "\"phone\":{\"type\":\"string\"},"
                + "\"role\":{\"type\":\"string\"},"
                + "\"status\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // LoginResponse
                + "\"LoginResponse\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"status\":{\"type\":\"string\"},"
                + "\"message\":{\"type\":\"string\"},"
                + "\"token\":{\"type\":\"string\"},"
                + "\"user\":{\"$ref\":\"#/components/schemas/User\"}"
                + "}"
                + "},"
                // ForgotPasswordRequest
                + "\"ForgotPasswordRequest\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"email\":{\"type\":\"string\"}"
                + "},"
                + "\"required\":[\"email\"]"
                + "},"
                // StatusMessage
                + "\"StatusMessage\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"status\":{\"type\":\"string\"},"
                + "\"message\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // EventList (dùng cho /api/events)
                + "\"EventList\":{"
                + "\"type\":\"object\","
                + "\"properties\":{"
                + "\"eventId\":{\"type\":\"integer\"},"
                + "\"title\":{\"type\":\"string\"},"
                + "\"description\":{\"type\":\"string\"},"
                + "\"startTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"endTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "\"maxSeats\":{\"type\":\"integer\"},"
                + "\"status\":{\"type\":\"string\"}"
                + "}"
                + "},"
                // Category Ticket
                + "\"CategoryTicket\":{"
                + "  \"type\":\"object\","
                + "  \"properties\":{"
                + "     \"categoryTicketId\":{\"type\":\"integer\"},"
                + "     \"name\":{\"type\":\"string\"},"
                + "     \"price\":{\"type\":\"number\",\"format\":\"double\"},"
                + "     \"maxQuantity\":{\"type\":\"integer\"},"
                + "     \"status\":{\"type\":\"string\"}"
                + "  }"
                + "},"
                //Seat List
                    + "\"Seat\":{"
                + "  \"type\":\"object\","
                + "  \"properties\":{"
                + "     \"seatId\":{\"type\":\"integer\"},"
                + "     \"areaId\":{\"type\":\"integer\"},"   // 🔁
                + "     \"seatCode\":{\"type\":\"string\"},"
                + "     \"rowNo\":{\"type\":\"string\"},"
                + "     \"colNo\":{\"type\":\"string\"},"
                + "     \"status\":{\"type\":\"string\"},"
                + "     \"seatType\":{\"type\":\"string\"}"
                + "  }"
                + "},"
                     + "\"SeatResponse\":{"
                + "  \"type\":\"object\","
                + "  \"properties\":{"
                + "     \"areaId\":{\"type\":\"integer\"},"        // 🔁
                + "     \"seatType\":{\"type\":\"string\"},"
                + "     \"total\":{\"type\":\"integer\"},"
                + "     \"seats\":{"
                + "        \"type\":\"array\","
                + "        \"items\":{\"$ref\":\"#/components/schemas/Seat\"}"
                + "     }"
                + "  }"
                + "},"
                // Event Detail 
                + "\"EventDetail\":{"
                + "  \"type\":\"object\","
                + "  \"properties\":{"
                + "     \"eventId\":{\"type\":\"integer\"},"
                + "     \"title\":{\"type\":\"string\"},"
                + "     \"description\":{\"type\":\"string\"},"
                + "     \"startTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "     \"endTime\":{\"type\":\"string\",\"format\":\"date-time\"},"
                + "     \"maxSeats\":{\"type\":\"integer\"},"
                + "     \"status\":{\"type\":\"string\"},"
                + "     \"venueName\":{\"type\":\"string\"},"
                + "     \"speakerName\":{\"type\":\"string\"},"
                + "     \"tickets\":{"
                + "        \"type\":\"array\","
                + "        \"items\":{\"$ref\":\"#/components/schemas/CategoryTicket\"}"
                + "     }"
                + "  }"
                + "},"
                + "}" // end schemas
                + "}" // end components
                + "}";  // end root

        try ( PrintWriter out = resp.getWriter()) {
            out.print(json);
            out.flush();
        }
    }
}
